[workspace]
resolver = "2"
members = [
    "game",
    "engine",
    "editor",
]

[patch.crates-io]
imgui = { git = "https://github.com/eliasstepanik/imgui-rs" }
imgui-sys = { git = "https://github.com/eliasstepanik/imgui-rs" }