[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "25.0.2"
winit = "0.30"
glam = { version = "0.30.4", features = ["bytemuck"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }