name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  preflight:
    name: Preflight Checks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Install just
      uses: extractions/setup-just@v2
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        # Install X11 and Wayland development libraries
        sudo apt-get install -y \
          libxkbcommon-dev \
          libwayland-dev \
          libxcb-shape0-dev \
          libxcb-xfixes0-dev \
          libxkbcommon-x11-dev \
          libvulkan-dev \
          mesa-vulkan-drivers
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run preflight checks
      run: just preflight

  # Additional job for different platforms
  cross-platform:
    name: Cross-platform Build
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install just
      uses: extractions/setup-just@v2
    
    - name: Build
      run: just build